//! Generated gRPC types for the DiLoCo coordinator/worker protocol.

pub mod proto {
    // Generated by build.rs into OUT_DIR; included directly to avoid depending
    // on a particular `include_proto!` macro location across tonic versions.
    include!(concat!(env!("OUT_DIR"), "/diloco.rs"));
}

pub use proto::diloco_client::DilocoClient;
pub use proto::diloco_server::{Diloco, DilocoServer};
pub use proto::{AllReduceRequest, InitRequest, ParamMsg};

/// Parameter payloads are model-sized (tens of MB), well above tonic's 4 MB
/// default. Both client and server must raise their limits to this.
pub const MAX_MESSAGE_SIZE: usize = 256 * 1024 * 1024;
